# Generated by Django 3.2.9 on 2021-11-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='título',
            new_name='titulo',
        ),
    ]
